/*
SQLyog Enterprise - MySQL GUI v7.15 
MySQL - 5.5.21 : Database - ck000001
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE /*!32312 IF NOT EXISTS*/`ck000001` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_bin */;

USE `ck000001`;

/*Table structure for table `a701` */

DROP TABLE IF EXISTS `a701`;

CREATE TABLE `a701` (
  `A7_COD` int(11) NOT NULL AUTO_INCREMENT,
  `A7_DESCRICAO` varchar(60) COLLATE latin1_bin DEFAULT NULL,
  PRIMARY KEY (`A7_COD`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `a901` */

DROP TABLE IF EXISTS `a901`;

CREATE TABLE `a901` (
  `A9_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `A9_DESC` varchar(150) COLLATE latin1_bin DEFAULT NULL,
  `A9_STATUS` varchar(1) COLLATE latin1_bin DEFAULT NULL,
  `A9_CODREV` int(11) DEFAULT NULL,
  `A9_APP` int(11) DEFAULT NULL,
  PRIMARY KEY (`A9_CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `aa01` */

DROP TABLE IF EXISTS `aa01`;

CREATE TABLE `aa01` (
  `AA_CODCHK` int(11) NOT NULL,
  `AA_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `AA_DESC` varchar(120) COLLATE latin1_bin DEFAULT NULL,
  `AA_CODERP` int(11) DEFAULT NULL,
  `AA_CODANT` int(11) DEFAULT NULL,
  PRIMARY KEY (`AA_CODIGO`,`AA_CODCHK`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `ab01` */

DROP TABLE IF EXISTS `ab01`;

CREATE TABLE `ab01` (
  `AB_CODCHK` int(11) NOT NULL,
  `AB_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `AB_DESC` varchar(40) COLLATE latin1_bin DEFAULT NULL,
  `AB_CODANT` int(11) DEFAULT NULL,
  PRIMARY KEY (`AB_CODIGO`,`AB_CODCHK`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `ac01` */

DROP TABLE IF EXISTS `ac01`;

CREATE TABLE `ac01` (
  `AC_CODCHK` int(11) NOT NULL,
  `AC_CODTIPO` int(11) NOT NULL,
  `AC_CODGRUPO` int(11) NOT NULL,
  PRIMARY KEY (`AC_CODCHK`,`AC_CODTIPO`,`AC_CODGRUPO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `ad01` */

DROP TABLE IF EXISTS `ad01`;

CREATE TABLE `ad01` (
  `AD_CODCHK` int(11) NOT NULL,
  `AD_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `AD_PERGUNTA` varchar(500) COLLATE latin1_bin DEFAULT NULL,
  `AD_TIPO` varchar(1) COLLATE latin1_bin DEFAULT NULL,
  `AD_STATUS` varchar(1) COLLATE latin1_bin DEFAULT NULL,
  `AD_CODANT` int(11) DEFAULT NULL,
  `AD_SEQ` int(11) DEFAULT NULL,
  PRIMARY KEY (`AD_CODIGO`,`AD_CODCHK`)
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `ae01` */

DROP TABLE IF EXISTS `ae01`;

CREATE TABLE `ae01` (
  `AE_CODCHK` int(11) NOT NULL,
  `AE_GRUPO` int(11) NOT NULL,
  `AE_CODPER` int(11) NOT NULL,
  PRIMARY KEY (`AE_CODCHK`,`AE_GRUPO`,`AE_CODPER`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `af01` */

DROP TABLE IF EXISTS `af01`;

CREATE TABLE `af01` (
  `AF_CODCHK` int(11) NOT NULL,
  `AF_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `AF_RESPOSTA` varchar(50) COLLATE latin1_bin DEFAULT NULL,
  `AF_CODANT` int(11) DEFAULT NULL,
  PRIMARY KEY (`AF_CODCHK`,`AF_CODIGO`),
  KEY `AF_CODIGO` (`AF_CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `ag01` */

DROP TABLE IF EXISTS `ag01`;

CREATE TABLE `ag01` (
  `AG_CODCHK` int(11) NOT NULL,
  `AG_PERPAI` int(11) NOT NULL,
  `AG_PERFILHA` int(11) NOT NULL,
  `AG_CODRESPAI` int(11) DEFAULT NULL,
  PRIMARY KEY (`AG_CODCHK`,`AG_PERPAI`,`AG_PERFILHA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `ah01` */

DROP TABLE IF EXISTS `ah01`;

CREATE TABLE `ah01` (
  `AH_CODCHK` int(11) NOT NULL,
  `AH_CODPER` int(11) NOT NULL,
  `AH_CODRES` int(11) NOT NULL,
  `AH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AH_IDANT` int(11) DEFAULT NULL,
  PRIMARY KEY (`AH_CODCHK`,`AH_CODPER`,`AH_CODRES`),
  UNIQUE KEY `AF_ID` (`AH_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=19319 DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `ai01` */

DROP TABLE IF EXISTS `ai01`;

CREATE TABLE `ai01` (
  `AI_CODCHK` int(11) NOT NULL,
  `AI_CODPER` int(11) NOT NULL,
  `AI_CODRES` int(11) NOT NULL,
  PRIMARY KEY (`AI_CODCHK`,`AI_CODPER`,`AI_CODRES`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `aj01` */

DROP TABLE IF EXISTS `aj01`;

CREATE TABLE `aj01` (
  `AJ_CODCHK` int(11) NOT NULL,
  `AJ_CODGRP` int(11) NOT NULL,
  `AJ_CODRES` int(11) NOT NULL,
  `AJ_QTDRESTR` int(11) DEFAULT NULL,
  PRIMARY KEY (`AJ_CODCHK`,`AJ_CODRES`,`AJ_CODGRP`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `ba01` */

DROP TABLE IF EXISTS `ba01`;

CREATE TABLE `ba01` (
  `BA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BA_PLACA` varchar(8) COLLATE latin1_bin NOT NULL,
  `BA_CHIP` varchar(30) COLLATE latin1_bin NOT NULL,
  `BA_TIPO` int(11) DEFAULT NULL,
  `BA_DESC` varchar(50) COLLATE latin1_bin DEFAULT NULL,
  PRIMARY KEY (`BA_PLACA`,`BA_CHIP`),
  UNIQUE KEY `BA_ID` (`BA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=213784 DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `bb01` */

DROP TABLE IF EXISTS `bb01`;

CREATE TABLE `bb01` (
  `BB_CODCHK` int(11) DEFAULT NULL,
  `BB_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `BB_CODUSER` int(11) DEFAULT NULL,
  `BB_PLACA` varchar(8) COLLATE latin1_bin DEFAULT NULL,
  `BB_CHIP` varchar(30) COLLATE latin1_bin DEFAULT NULL,
  `BB_DTCHECK` date DEFAULT NULL,
  `BB_HRCHECK` varchar(5) COLLATE latin1_bin DEFAULT NULL,
  `BB_OBS` varchar(500) COLLATE latin1_bin DEFAULT NULL,
  `BB_STATUS` varchar(2) COLLATE latin1_bin DEFAULT NULL,
  PRIMARY KEY (`BB_CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=87 DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `bc01` */

DROP TABLE IF EXISTS `bc01`;

CREATE TABLE `bc01` (
  `BC_CODCHK` int(11) NOT NULL,
  `BC_CODIGO` int(11) NOT NULL,
  `BC_CODPER` int(11) NOT NULL,
  `BC_ID` int(11) NOT NULL,
  PRIMARY KEY (`BC_CODCHK`,`BC_CODIGO`,`BC_ID`,`BC_CODPER`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
